name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - develop
      - 'releases/*'
      - test

jobs:
  build: # make sure build/ci work properly
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: create .env file
      run: |
        env > .env
    - name: run the make command
      run: |
        make dev.build_image
        make dev.all
  test: # make sure the action works on a clean machine without building
    runs-on: self-hosted
    env:
      REGISTRY_NAME: '1234567890.dkr.ecr.ap-northeast-1.amazonaws.com'
      CONTAINERKOJO_ENV: 'test'
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        image_name: image_assembly_line/test
        target: test.build_image
        no_push: true
